version: "3"

dotenv: [ '.env' ]

vars:
  LOCAL_WORKSPACE_FOLDER: "{{.LOCAL_WORKSPACE_FOLDER | default '.'}}"

tasks:
  docker-compose:
    internal: true
    # cmd: docker compose {{.COMPOSE}}
    cmd: docker compose --project-directory {{.LOCAL_WORKSPACE_FOLDER}} {{.COMPOSE}}

  init:
    desc: Первый запуск
    cmds:
      - task: pull
      - task: up

  docker-up:
    desc: Запустить контейнеры
    aliases: [ up ]
    cmds:
      - task: docker-compose
        vars:
          COMPOSE: up -d
      - task: status

  docker-pull:
    desc: Загрузить образы
    aliases: [ pull ]
    cmds:
      - task: docker-compose
        vars:
          COMPOSE: pull

  docker-build:
    desc: Build образов
    aliases: [ build ]
    cmds:
      - task: docker-compose
        vars:
          COMPOSE: build

  docker-down:
    desc: Остановить контейнеры
    aliases: [ down ]
    cmds:
      - task: docker-compose
        vars:
          COMPOSE: down

  docker-restart:
    desc: Перезапустить все контейнеры
    aliases: [ restart ]
    cmds:
      - task: down
      - task: up

  docker-pause:
    desc: Пауза контейнеров
    aliases: [ pause ]
    cmds:
      - task: docker-compose
        vars:
          COMPOSE: pause

  docker-unpause:
    desc: Пуск контейнеров
    aliases: [ unpause, play ]
    cmds:
      - task: docker-compose
        vars:
          COMPOSE: unpause

  docker-ps:
    desc: Список контейнеров
    aliases: [ ps ]
    cmds:
      - task: docker-compose
        vars:
          COMPOSE: ps

  docker-clean:
    desc: Удалить volumes и кэш laravel
    aliases: [ clean ]
    cmds:
      - task: optimize-clear
      - cmd: docker compose down -v --remove-orphans

  status:
    desc: Статус приложения
    cmds:
      - echo -e "\033[1;36m========================================\033[0m"
      - echo -e "\033[1;32m✔ Application is ready!\033[0m"
      - echo -e "\033[1;36m========================================\033[0m"
      - echo ""
      - echo -e "\033[1;33mMLFlow:\033[0m        http://mlflow.llm.test"
      - echo -e "\033[1;33mvLLM:\033[0m          http://vllm.llm.test"
      - echo ""
      - echo -e "\033[1;33mPrometheus:\033[0m    http://prometheus.llm.test"
      - echo -e "\033[1;33mGrafana:\033[0m       http://grafana.llm.test"
      - echo ""
      - echo -e "\033[1;33mMinIO:\033[0m         http://minio.llm.test"
      - echo -e "\033[1;33mPostgres:\033[0m      127.0.0.1:5432"
      - echo ""
      - echo -e "\033[1;33mTraefik:\033[0m       http://127.0.0.1:8888"
      - echo -e "\033[1;36m========================================\033[0m"
    silent: true
